GO_EASY_ON_ME=1

include theos/makefiles/common.mk

BUNDLE_NAME = AECustomizerPreferences
AECustomizerPreferences_FILES = AECustomizerPreferences.mm
AECustomizerPreferences_INSTALL_PATH = /Library/AssistantExtensions/Customizer.assistantExtension/
AECustomizerPreferences_FRAMEWORKS = UIKit
AECustomizerPreferences_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
