.TH "aiml::cMatchLog" 3 "3 Feb 2006" "Version 0.6" "libaiml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiml::cMatchLog \- This structure is used to hold the nodes of the tree that matched the user's input, that and topic.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::list< std::string > \fBpattern\fP"
.br
.ti -1c
.RI "std::list< std::string > \fBthat\fP"
.br
.ti -1c
.RI "std::list< std::string > \fBtopic\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This structure is used to hold the nodes of the tree that matched the user's input, that and topic. 

The lists hold one token (ie, a word with no spaces) of the corresponding match.
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libaiml from the source code.
